create table if not exists public.user_entitlements (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  plan_id text not null check (plan_id in ('plus')),
  status text not null check (status in ('active', 'manual_grant', 'past_due', 'overdue', 'cancelled', 'expired')),
  source text not null check (source in ('asaas', 'manual_grant', 'system')),
  provider text,
  provider_customer_id text,
  provider_subscription_id text,
  granted_by uuid references public.profiles(id) on delete set null,
  reason text,
  starts_at timestamptz not null default now(),
  expires_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists user_entitlements_user_plan_source_idx
  on public.user_entitlements(user_id, plan_id, source);

create table if not exists public.entitlement_audit_events (
  id bigint generated by default as identity primary key,
  actor_user_id uuid references public.profiles(id) on delete set null,
  target_user_id uuid not null references public.profiles(id) on delete cascade,
  action text not null,
  plan_id text not null default 'plus',
  source text not null,
  reason text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.billing_events (
  id bigint generated by default as identity primary key,
  provider text not null,
  provider_event_id text not null,
  event_type text not null,
  payload jsonb not null,
  processed_at timestamptz not null default now(),
  unique(provider, provider_event_id)
);

alter table public.user_entitlements enable row level security;
alter table public.entitlement_audit_events enable row level security;
alter table public.billing_events enable row level security;

create policy "Users can read own entitlements"
  on public.user_entitlements for select
  using (auth.uid() = user_id);

create policy "Super admins can read all entitlements"
  on public.user_entitlements for select
  using (
    exists (
      select 1 from public.profiles
      where id = auth.uid()
        and (is_super_user = true or username = 'sharkcoder')
    )
  );

create policy "Super admins can manage entitlements"
  on public.user_entitlements for all
  using (
    exists (
      select 1 from public.profiles
      where id = auth.uid()
        and (is_super_user = true or username = 'sharkcoder')
    )
  )
  with check (
    exists (
      select 1 from public.profiles
      where id = auth.uid()
        and (is_super_user = true or username = 'sharkcoder')
    )
  );

create policy "Super admins can read audit events"
  on public.entitlement_audit_events for select
  using (
    exists (
      select 1 from public.profiles
      where id = auth.uid()
        and (is_super_user = true or username = 'sharkcoder')
    )
  );

create policy "Super admins can insert audit events"
  on public.entitlement_audit_events for insert
  with check (
    exists (
      select 1 from public.profiles
      where id = auth.uid()
        and (is_super_user = true or username = 'sharkcoder')
    )
  );

update public.profiles
set is_super_user = true
where username = 'sharkcoder';
