-- Secure Asaas billing schema for SharkType.
-- All billing writes are server/service-role only. Authenticated users can only read their own state.

create table if not exists public.billing_checkouts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  provider text not null default 'asaas' check (provider = 'asaas'),
  purpose text not null check (purpose in ('plus_subscription', 'sandbox_test')),
  external_reference text not null unique,
  provider_checkout_id text unique,
  provider_customer_id text,
  status text not null default 'creating' check (status in ('creating', 'active', 'paid', 'canceled', 'expired', 'failed')),
  amount numeric(10,2) not null check (amount > 0),
  currency text not null default 'BRL' check (currency = 'BRL'),
  sandbox boolean not null default true,
  checkout_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists billing_checkouts_user_created_idx
  on public.billing_checkouts(user_id, created_at desc);
create index if not exists billing_checkouts_customer_idx
  on public.billing_checkouts(provider_customer_id)
  where provider_customer_id is not null;

create table if not exists public.billing_subscriptions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  provider text not null default 'asaas' check (provider = 'asaas'),
  purpose text not null default 'plus_subscription' check (purpose in ('plus_subscription', 'sandbox_test')),
  provider_subscription_id text not null,
  provider_customer_id text,
  status text not null,
  cycle text,
  amount numeric(10,2),
  next_due_date date,
  sandbox boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(provider, provider_subscription_id)
);

create index if not exists billing_subscriptions_user_idx
  on public.billing_subscriptions(user_id, created_at desc);
create index if not exists billing_subscriptions_customer_idx
  on public.billing_subscriptions(provider_customer_id)
  where provider_customer_id is not null;

create table if not exists public.user_entitlements (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  plan_id text not null default 'plus' check (plan_id in ('plus')),
  status text not null check (status in ('active', 'manual_grant', 'past_due', 'overdue', 'cancelled', 'expired')),
  source text not null check (source in ('asaas', 'manual_grant', 'system')),
  provider text,
  provider_customer_id text,
  provider_subscription_id text,
  granted_by uuid references public.profiles(id) on delete set null,
  reason text,
  starts_at timestamptz not null default now(),
  expires_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists user_entitlements_user_plan_source_idx
  on public.user_entitlements(user_id, plan_id, source);
create index if not exists user_entitlements_subscription_idx
  on public.user_entitlements(provider, provider_subscription_id)
  where provider_subscription_id is not null;

create table if not exists public.entitlement_audit_events (
  id bigint generated by default as identity primary key,
  actor_user_id uuid references public.profiles(id) on delete set null,
  target_user_id uuid not null references public.profiles(id) on delete cascade,
  action text not null,
  plan_id text not null default 'plus',
  source text not null,
  reason text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.billing_events (
  id bigint generated by default as identity primary key,
  provider text not null,
  provider_event_id text not null,
  event_type text not null,
  payload jsonb not null,
  received_at timestamptz not null default now(),
  processed_at timestamptz,
  processing_error text,
  unique(provider, provider_event_id)
);

create or replace function public.touch_billing_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists billing_checkouts_touch_updated_at on public.billing_checkouts;
create trigger billing_checkouts_touch_updated_at
before update on public.billing_checkouts
for each row execute function public.touch_billing_updated_at();

drop trigger if exists billing_subscriptions_touch_updated_at on public.billing_subscriptions;
create trigger billing_subscriptions_touch_updated_at
before update on public.billing_subscriptions
for each row execute function public.touch_billing_updated_at();

drop trigger if exists user_entitlements_touch_updated_at on public.user_entitlements;
create trigger user_entitlements_touch_updated_at
before update on public.user_entitlements
for each row execute function public.touch_billing_updated_at();

alter table public.billing_checkouts enable row level security;
alter table public.billing_subscriptions enable row level security;
alter table public.user_entitlements enable row level security;
alter table public.entitlement_audit_events enable row level security;
alter table public.billing_events enable row level security;

-- Remove policies left by the abandoned entitlement migration, including username-based admin checks.
drop policy if exists "Users can read own entitlements" on public.user_entitlements;
drop policy if exists "Super admins can read all entitlements" on public.user_entitlements;
drop policy if exists "Super admins can manage entitlements" on public.user_entitlements;
drop policy if exists "Super admins can read audit events" on public.entitlement_audit_events;
drop policy if exists "Super admins can insert audit events" on public.entitlement_audit_events;

revoke all on public.billing_checkouts from anon, authenticated;
revoke all on public.billing_subscriptions from anon, authenticated;
revoke all on public.user_entitlements from anon, authenticated;
revoke all on public.entitlement_audit_events from anon, authenticated;
revoke all on public.billing_events from anon, authenticated;

grant select on public.billing_checkouts to authenticated;
grant select on public.billing_subscriptions to authenticated;
grant select on public.user_entitlements to authenticated;

grant all on public.billing_checkouts to service_role;
grant all on public.billing_subscriptions to service_role;
grant all on public.user_entitlements to service_role;
grant all on public.entitlement_audit_events to service_role;
grant all on public.billing_events to service_role;
grant usage, select on sequence public.entitlement_audit_events_id_seq to service_role;
grant usage, select on sequence public.billing_events_id_seq to service_role;

create policy "Users can read own billing checkouts"
  on public.billing_checkouts for select to authenticated
  using (auth.uid() = user_id);

create policy "Users can read own billing subscriptions"
  on public.billing_subscriptions for select to authenticated
  using (auth.uid() = user_id);

create policy "Users can read own entitlements"
  on public.user_entitlements for select to authenticated
  using (auth.uid() = user_id);
